import {
  contactIcon,
  editProfile,
  faqIcon,
  forwardIcon,
  howIcon,
  logoutIcon,
  myOrderIcon,
  notificationIcon,
  privacyIcon,
  storyIcon,
  termsIcon,
} from '../assets/images';
import {WIDTH} from './Dimensions';

export const dataProfile = [
  {
    id: 1,
    icon: editProfile,
    title: 'EDIT PROFILE',
    forward: forwardIcon,
    border: 1.5,
    margin: WIDTH * 0.05,
  },
  {
    id: 2,
    icon: myOrderIcon,
    title: 'MY ORDERS',
    forward: forwardIcon,
    border: 1.5,
    margin: WIDTH * 0.05,
  },
  {
    id: 3,
    icon: notificationIcon,
    title: 'NOTIFICATIONS',
    forward: forwardIcon,
    border: 4,
  },
  {
    id: 4,
    icon: storyIcon,
    title: 'THE STORY OF QURATION',
    forward: forwardIcon,
    border: 1.5,
    margin: WIDTH * 0.05,
  },
  {
    id: 5,
    icon: howIcon,
    title: 'HOW TO SHOP',
    forward: forwardIcon,
    border: 1.5,
    margin: WIDTH * 0.05,
  },
  {
    id: 6,
    icon: faqIcon,
    title: 'FAQS',
    forward: forwardIcon,
    border: 1.5,
    margin: WIDTH * 0.05,
  },
  {
    id: 7,
    icon: termsIcon,
    title: 'TERMS & CONDITIONS',
    forward: forwardIcon,
    border: 1.5,
    margin: WIDTH * 0.05,
  },
  {
    id: 8,
    icon: privacyIcon,
    title: 'PRIVACY POLICY',
    forward: forwardIcon,
    border: 4,
  },
  {
    id: 9,
    icon: contactIcon,
    title: 'CONTACT US',
    forward: forwardIcon,
    border: 4,
  },
  {
    id: 10,
    icon: logoutIcon,
    title: 'LOGOUT',
  },
];
